import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

const Container = ({ children }) => {
  return (
    <div className="bg-gray-50 dark:bg-gray-900 lg:container py-4">
      <Head>
        <title>aruniverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center px-8">
        <Header />
        <main
          id="skip"
          className="flex flex-col justify-center bg-gray-50 px-8 dark:bg-gray-900"
        >
          {children}
          <Footer />
        </main>
      </div>
    </div>
  );
};

export default Container;
