import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

const Container = ({ children }) => {
  return (
    <div className="h-screen bg-gray-50 dark:bg-gray-900">
      <Head>
        <title>aruniverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:site_name" content="Arun George" />
        <meta name="twitter:site" content="@aruniverse" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto flex h-full flex-col px-8 lg:container">
        <Header />
        <main id="skip" className="flex-grow justify-center px-4">
          {children}
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Container;
