import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

const Container = ({ children }) => {
  return (
    <div className="h-screen">
      <Head>
        <title>aruniverse</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta property="og:site_name" content="Arun George" />
        <meta name="twitter:site" content="@aruniverse" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto flex h-full max-w-screen-lg flex-col sm:px-8 px-6 py-2">
        <Header />
        <main id="skip" className="flex-grow justify-center sm:px-4 pt-2 pb-4 px-0">
          {children}
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Container;
