import { Html, Head, Main, NextScript } from 'next/document';

const Document = () => {
  return (
    <Html lang="en">
      <Head>
        <meta content="" name="google-site-verification" />
        <meta name="description" content="Generated by create next app" />
        <meta property="og:site_name" content="Arun George" />
        <meta name="twitter:site" content="@aruniverse" />
      </Head>
      <body className="bg-gray-50 text-black dark:bg-gray-900 dark:text-white">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
