import { useEffect } from "react";
import Head from "next/head";
import { marked } from "https://cdn.skypack.dev/marked";
import confetti from "https://cdn.skypack.dev/canvas-confetti";
import hljs from "https://cdn.skypack.dev/highlight.js";

const EsmHome = ({ content }) => {
  useEffect(() => {
    confetti({
      particleCount: 150,
      spread: 180,
    });
  }, []);

  return (
    <>
      <Head>
        <title>aruniverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main dangerouslySetInnerHTML={{ __html: content }} />
      <footer>{`${new Date().getFullYear()} © Arun George`}</footer>
    </>
  );
};

export const getStaticProps = async () => {
  const rawContent = await fetch(
    "https://gist.githubusercontent.com/aruniverse/122e4d2ad369885b50a71c99b2cad752/raw/22234b6b05ba981a76ef0491cc986660b82dbe7c/test.md"
  );
  const markdown = await rawContent.text();
  // console.log(markdown);

  marked.setOptions({
    // highlight: function (code, language) {
    //   // console.log(code, language);
    //   return hljs.highlight(code, { language: "tex" }).value;
    // },
    highlight: (code, language) => {
      // return hljs.highlight(code, { language: "tex" }).value;
      return hljs.highlight(code, { language }).value;
    },
  });

  return {
    props: {
      content: marked(markdown),
    },
  };
};

export default EsmHome;
